kind: pipeline
type: docker
name: Build, Push, and Deploy

steps:
  # 克隆代码
  #- name: clone-repo
  #  image: alpine/git
  #  commands:
  #    - git clone https://github.com/maypu/AirFile.git .
  #    - git checkout $DRONE_COMMIT

  # 登录 Docker Hub
  - name: docker-login
    image: docker
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # 构建 Docker 镜像，推送 Docker 镜像到 Docker Hub
  - name: build-and-push
    image: plugins/docker
    settings:
      # 如果 Dockerfile 不在根目录，需指定路径
      dockerfile: Dockerfile
      # Docker Hub 仓库名
      repo: maypu/airfile
      # 镜像标签
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret docker_password

  # SSH 到服务器并启动容器（使用环境变量）
  - name: ssh-deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: ssh_port
      script:
        - docker stop airfile || true
        - docker rm airfile || true
        - docker run -d \
          -p ${APP_PORT}:8086 \
          -v ${DOCKER_DIR}/airfile/database:/app/database \
          -v ${DOCKER_DIR}/airfile/files:/app/files \
          --name=airfile \
          --restart=always \
          maypu/airfile:latest
    environment:
      # 默认宿主机端口 8086
      APP_PORT: 8086
      # 默认宿主机挂载路径
      DOCKER_DIR: /home/maypu/docker
  
  - name: debug
    image: alpine
    commands:
        # 查看 Drone 默认克隆的目录
        - ls -la /drone/src